name: Build

on:
  push:
    branches-ignore:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: test
      uses: ./.github/workflows/test