name: Test and Prerelease

on:
  push:
    branches:
    - main

jobs:
  Prerelease:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Unit Tests
      uses: ./.github/workflows/test
    - name: Package
      uses: ./.github/workflows/package
      with:
        version: latest

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: latest
        files: |
          *.ext