name: Test and Prerelease

on:
  push:

jobs:
  Test and Prerelease:
    runs-on: ubuntu-latest

    steps:
    - name: Unit Tests
      uses: ./.github/workflows/test
    - name: Package
      uses: ./.github/workflows/package
      with:
        version: latest

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          *.ext